### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/vim-candle#3]
- [x] Explicitly passes source-script arguments
- [x] Add choose action mapping
- [x] Works items source
- [x] Remove autoload/candle/source.vim
- [x] Design action resolution
- [ ] Create Public API
- [ ] Design source specific rpc-methods.
- [ ] Design event handling
- [ ] Refactor `context.vim`, `render/*.vim`
- [ ] Test on windows
- [ ] Test on Linux
- [ ] Create docs
- [ ] Organize variable names params and args
- [ ] Context.state key can be removed?

**Comment by hrsh7th** [comment]
Design source creation.

Currently, source returns `script.path`, `script.args` and other params.

But we sometimes want to re-use `item` source (It means we want to create only one function).

So we should provide `helper` functions like following.

```viml

function! candle#source#sample#source#get() abort
  return candle#helper#create_function_source({
    'name': 'sample',
    'source': function('s:source'),
  }, {
    'action': {
      'default': 'edit'
    }
  })
endfunction

function! s:source() abort
  let l:items = []
  for l:bufnr in range(1, bufnr('$'))
    ...
  endfor
  return l:items
endfunction
```
